services:
  api:
    container_name: pricing-model-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    networks:
      - app-network
    volumes:
      - .:/app

  app:
    container_name: pricing-model-ui
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    depends_on:
      - api
    networks:
      - app-network
    volumes:  
      - .:/app

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: app-network