services:
  api:
    container_name: pricing-model-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  app:
    container_name: pricing-model-ui
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:  
      - .:/app